version: '3.8'

services:
  place-service:
    build: Flask/microservices/place-service/
    networks:
      - app-network

  distance-service:
    build: Flask/microservices/distance-service/
    networks:
      - app-network

  route1-service:
    build: Flask/microservices/route1-service/
    networks:
      - app-network
  
  route2-service:
    build: Flask/microservices/route2-service/
    networks:
      - app-network
    
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    ports:
      - 8080:8080

networks:
  app-network: