name: "Temp workflow - store SSH key"

on: 
  workflow_dispatch

jobs:
  run_benchmark:
    name: Store SSH key
    runs-on: ubuntu-latest
    
    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Store ssh key
        run: |
          mkdir .ssh/
          echo "$SSH_KEY" > .ssh/admin.pem
          chmod 600 .ssh/admin.pem
        shell: bash
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
